name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: pip install --debug -r pip-local-freeze.txt
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
